FROM alpine:latest

ARG PYTHON_VERSION=3.12.12

RUN mkdir /work

WORKDIR /work

RUN apk update && apk add --no-cache \
    curl \
    gcc \
    musl \
    patchelf \
    musl-dev

# TODO: req.txt for client deps or simiar
RUN curl -LsSf https://astral.sh/uv/install.sh | sh && \
    source $HOME/.local/bin/env && \
    uv python install python3.12 && \
    uv venv /work/venv && source /work/venv/bin/activate && \
    uv pip install nuitka httpx pydantic
